package fs;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import static fs.Fs.countno;
import javax.swing.JOptionPane;
import static fs.Fs.recs;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileNotFoundException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.util.Scanner;
/**
 *
 * @author Rakshitha.R
 */
public class delete extends javax.swing.JFrame {

    /**
     * Creates new form search1
     */
    public delete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Enter ID");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 454, 128, 46));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 454, 128, 46));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 338, 449, 47));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("IMPLEMENTATION OF B+ TREE TECHNIQUE USING DOCTOR RECORDS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 63, 879, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SEARCH");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 244, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1sHo5Z.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, -1, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:  
        String name,fees,spec,phone,count;
        String[] nodes=new String[100];
        btree b = new btree();
        int choice=1,key=1,no = 0,rkey;
        try {
            no=countno();

            System.out.println("No. of records: "+no+"\n");
            for(int i=0;i<=no;i++)
            recs[i]=new records();
            BufferedReader f3 = new BufferedReader(new FileReader("C:\\Users\\Rakshitha.R\\Dropbox\\My PC (Rakshitha)\\Desktop\\pbl\\fsproject_5\\src\\bplus.txt"));
            for(int i=0;i<=no;i++)
            {
                String lineRead=f3.readLine();
                String [] st = lineRead.split("\\|");
                recs[i].keyf=st[0];
                recs[i].name=st[1];
                recs[i].fee=st[2];
                recs[i].spec=st[3];
                recs[i].phone=st[4];
                rkey=Integer.valueOf(recs[i].keyf);
                b.insert(rkey);
            }
            f3.close();

            key=Integer.valueOf(jTextField1.getText());
            b.search(key);
            f3=new BufferedReader(new FileReader("C:\\Users\\Rakshitha.R\\Dropbox\\My PC (Rakshitha)\\Desktop\\pbl\\fsproject_5\\src\\bplus.txt"));
            for(int i=0;i<=no;i++)
            {
                String lineRead=f3.readLine();
                String [] t=lineRead.split("\\|");
                recs[i].keyf=t[0];
                recs[i].name=t[1];
                recs[i].fee=t[2];
                recs[i].spec=t[3];
                recs[i].phone=t[4];
                rkey=Integer.valueOf(recs[i].keyf);
                if (key == rkey) {
                    String oldLine = String.format("%s|%s|%s|%s|%s", key,recs[i].name,recs[i].fee,recs[i].spec,recs[i].phone);
                    //String oldLine = ""+key+"|"+recs[i].name+"|"+recs[i].fee+"|"+recs[i].spec+"|"+recs[i].phone+"";
                    String filePath = "C:\\Users\\Rakshitha.R\\Dropbox\\My PC (Rakshitha)\\Desktop\\pbl\\fsproject_5\\src\\bplus.txt";
                    Scanner sc = new Scanner(new File(filePath));
                    StringBuffer buffer = new StringBuffer();
                    while (sc.hasNextLine()) {
                        buffer.append(sc.nextLine() + System.lineSeparator());
                    }
                    String fileContents = buffer.toString();
                    String newLine="  ";
                    fileContents = fileContents.replaceAll(oldLine, newLine);
                    FileWriter writer = new FileWriter(filePath);
                    writer.append(fileContents);
                    writer.flush();
                    sc.close();
                    System.exit(0);
                }
            }
            f3.close();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null," not success");
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new options1().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new delete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
